name: Build & Release Printio

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build & Publish
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
